= Comparison with other messaging technologies

. Summary
|===
| Name | PubSub | Message Queue | Regex filtering | Geo filtering | Durable or not | Available in the browser | Hosted | On Premises

| TurtleQueue
| ✅
| ✅
| icon:check[role="red"] (coming soon)
| ✅
| ✅
| ✅
| ✅
| ✅

| RabbitMQ
| ❌
| ✅
| icon:star-half[role="orange"] (wildcard-only)
| ❌
| ✅
| ❌
| ❌
| ✅

| Apache Kafka
| ✅
| ✅
| ✅
| ❌
| ❌
| ❌
| ❌
| ✅

| Google Pubsub
| ✅
| ✅
| ✅
| ❌
| ❌
| ✅
| ❌
| ❌

|===



PubSub::
Can the platform be user with the semantics of a Publish/Subscribe model?

Message Queue::
Can the platform present the semantics of a message queue?

Regex filtering::
Can the user use a regex to choose where the messages will be published?

Geo filtering::
Can the user use a latitude/longitude/radius to decide where the messages will be published?

Durable or not::
Can the messages in a channel/topic/subscription be configured to be persisted to disk and not deleted after being acknowledged? Conversely, can they be configured to be deleted?

For instance Apache Kafka will always keep messages, even though the retention period is configurable. Google PubSub has pre-set rules on how long messages are kept.

Available in the browser::
can the platform be used directly from a browser or app?

Hosted::
is the platform available without the user having to install it on a server?

On Premises::
Can the platform be installed on a customer's server?
