= Reliability


== Acknowledgements

When sending a message, you want guarantees that it will arrive to it's destination.
The only way to be certain that the message arrived, is to have an acknowledgement sent from the recipient.

Acknowledgement is a built-in feature in TurtleQueue's SDK. For ease of use we automatically acknowledge the messages once your callback has been run, unless it threw an Exception, but you can control it manually yourself.

There are two steps to do so:

1. turn off `autoAck` when making a Turtle instance


2. call the acknowledge manually for every message susccesfully processed and the non-acknowledge for every message that has to be processed again


3. (optional) adjust the acknowledge timeout


If after sending a message to a recipient we do not get an acknowledgement response withing the alloted timeout, the message will be sent again for delivery, until it is finally acknowledged.

Because of this feature some consumers could see messages out-of-order, depending on the failures to process messages. This includes the case where a client disconnects while processing messages and fails to acknowledge them.

When the tradeof is between reliability and performance we will always choose reliability by default. This means that your commands are always persisted, not just kept in-memory before we acknowledge a message to be sent.


=== Positive Acknowledge

=== Negative Acknowledge

When a consumer does not consume a message successfully at a time, and wants to consume the message again, the consumer can send a negative acknowledgement to the broker, and then the broker will redeliver the message.

Messages can be negatively acknowledged one by one or cumulatively, which depends on the consumption subscription mode.

In the exclusive and failover subscription modes, consumers only negatively acknowledge the last message they have received.

In the shared and Key_Shared subscription modes, you can negatively acknowledge messages individually.

=== Acknowledgement timeout

When a message is not consumed successfully, and you want to trigger an automatic redelivery of the message, the default behavior is to rely on a timeout. There is an automatic re-delivery mechanism in place when the message takes too long to acknowledge (by default 10 seconds).
The timeout can be configured to be greater (but nor lower).

NOTE: Whenever possible, prefer using the negative acknowledgement instead of the acknowledgement timeout. Negative acknowledgement allow re-processing the message faster and avoids invalid redeliveries when the message processing time exceeds the acknowledgement timeout.
